config/routes.rb
Event::Application.routes.draw do
  resources :rooms

  resources :lecturers

  resources :conferences

  resources :tenants

  resources :tenant_users

  devise_for :users
  root to: "home#index"
  devise_for :users do
    post  "users" => "milia/registrations#create"
  end

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  belongs_to :tenant
  attr_accessible :description, :floor, :latitude, :longitude, :nombre
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :floor %><br />
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :tenant %><br />
    <%= f.text_field :tenant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Floor</th>
    <th>Description</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Tenant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.nombre %></td>
    <td><%= conference.floor %></td>
    <td><%= conference.description %></td>
    <td><%= conference.longitude %></td>
    <td><%= conference.latitude %></td>
    <td><%= conference.tenant %></td>
    <td><%= link_to 'Show', conference %></td>
    <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
    <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @conference.nombre %>
</p>

<p>
  <b>Floor:</b>
  <%= @conference.floor %>
</p>

<p>
  <b>Description:</b>
  <%= @conference.description %>
</p>

<p>
  <b>Longitude:</b>
  <%= @conference.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @conference.latitude %>
</p>

<p>
  <b>Tenant:</b>
  <%= @conference.tenant %>
</p>


<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>