config/routes.rb
Event::Application.routes.draw do
  resources :rooms

  resources :lecturers

  resources :conferences

  resources :tenants

  resources :tenant_users

  devise_for :users
  root to: "home#index"
  devise_for :users do
    post  "users" => "milia/registrations#create"
  end

end

app/models/tenant_user.rb
class TenantUser < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/tenant_users_controller.rb
class TenantUsersController < ApplicationController
  # GET /tenant_users
  # GET /tenant_users.json
  def index
    @tenant_users = TenantUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tenant_users }
    end
  end

  # GET /tenant_users/1
  # GET /tenant_users/1.json
  def show
    @tenant_user = TenantUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tenant_user }
    end
  end

  # GET /tenant_users/new
  # GET /tenant_users/new.json
  def new
    @tenant_user = TenantUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tenant_user }
    end
  end

  # GET /tenant_users/1/edit
  def edit
    @tenant_user = TenantUser.find(params[:id])
  end

  # POST /tenant_users
  # POST /tenant_users.json
  def create
    @tenant_user = TenantUser.new(params[:tenant_user])

    respond_to do |format|
      if @tenant_user.save
        format.html { redirect_to @tenant_user, notice: 'Tenant user was successfully created.' }
        format.json { render json: @tenant_user, status: :created, location: @tenant_user }
      else
        format.html { render action: "new" }
        format.json { render json: @tenant_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tenant_users/1
  # PUT /tenant_users/1.json
  def update
    @tenant_user = TenantUser.find(params[:id])

    respond_to do |format|
      if @tenant_user.update_attributes(params[:tenant_user])
        format.html { redirect_to @tenant_user, notice: 'Tenant user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tenant_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenant_users/1
  # DELETE /tenant_users/1.json
  def destroy
    @tenant_user = TenantUser.find(params[:id])
    @tenant_user.destroy

    respond_to do |format|
      format.html { redirect_to tenant_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tenant_users_helper.rb
module TenantUsersHelper
end

app/views/tenant_users/_form.html.erb
<%= form_for(@tenant_user) do |f| %>
  <% if @tenant_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant_user.errors.count, "error") %> prohibited this tenant_user from being saved:</h2>

      <ul>
      <% @tenant_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenant_users/edit.html.erb
<h1>Editing tenant_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant_user %> |
<%= link_to 'Back', tenant_users_path %>

app/views/tenant_users/index.html.erb
<h1>Listing tenant_users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tenant_users.each do |tenant_user| %>
  <tr>
    <td><%= link_to 'Show', tenant_user %></td>
    <td><%= link_to 'Edit', edit_tenant_user_path(tenant_user) %></td>
    <td><%= link_to 'Destroy', tenant_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tenant user', new_tenant_user_path %>

app/views/tenant_users/new.html.erb
<h1>New tenant_user</h1>

<%= render 'form' %>

<%= link_to 'Back', tenant_users_path %>

app/views/tenant_users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tenant_user_path(@tenant_user) %> |
<%= link_to 'Back', tenant_users_path %>