config/routes.rb
Event::Application.routes.draw do
  resources :rooms

  resources :lecturers

  resources :conferences

  resources :tenants

  resources :tenant_users

  devise_for :users
  root to: "home#index"
  devise_for :users do
    post  "users" => "milia/registrations#create"
  end

end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
  belongs_to :tenant
  attr_accessible :age, :foto, :last_name, :name, :profile
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  # GET /lecturers
  # GET /lecturers.json
  def index
    @lecturers = Lecturer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lecturers }
    end
  end

  # GET /lecturers/1
  # GET /lecturers/1.json
  def show
    @lecturer = Lecturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecturer }
    end
  end

  # GET /lecturers/new
  # GET /lecturers/new.json
  def new
    @lecturer = Lecturer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecturer }
    end
  end

  # GET /lecturers/1/edit
  def edit
    @lecturer = Lecturer.find(params[:id])
  end

  # POST /lecturers
  # POST /lecturers.json
  def create
    @lecturer = Lecturer.new(params[:lecturer])

    respond_to do |format|
      if @lecturer.save
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully created.' }
        format.json { render json: @lecturer, status: :created, location: @lecturer }
      else
        format.html { render action: "new" }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lecturers/1
  # PUT /lecturers/1.json
  def update
    @lecturer = Lecturer.find(params[:id])

    respond_to do |format|
      if @lecturer.update_attributes(params[:lecturer])
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lecturers/1
  # DELETE /lecturers/1.json
  def destroy
    @lecturer = Lecturer.find(params[:id])
    @lecturer.destroy

    respond_to do |format|
      format.html { redirect_to lecturers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/views/lecturers/_form.html.erb
<%= form_for(@lecturer) do |f| %>
  <% if @lecturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecturer.errors.count, "error") %> prohibited this lecturer from being saved:</h2>

      <ul>
      <% @lecturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_field :profile %>
  </div>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :tenant %><br />
    <%= f.text_field :tenant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lecturers/edit.html.erb
<h1>Editing lecturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecturer %> |
<%= link_to 'Back', lecturers_path %>

app/views/lecturers/index.html.erb
<h1>Listing lecturers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Last name</th>
    <th>Age</th>
    <th>Profile</th>
    <th>Foto</th>
    <th>Tenant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lecturers.each do |lecturer| %>
  <tr>
    <td><%= lecturer.name %></td>
    <td><%= lecturer.last_name %></td>
    <td><%= lecturer.age %></td>
    <td><%= lecturer.profile %></td>
    <td><%= lecturer.foto %></td>
    <td><%= lecturer.tenant %></td>
    <td><%= link_to 'Show', lecturer %></td>
    <td><%= link_to 'Edit', edit_lecturer_path(lecturer) %></td>
    <td><%= link_to 'Destroy', lecturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lecturer', new_lecturer_path %>

app/views/lecturers/new.html.erb
<h1>New lecturer</h1>

<%= render 'form' %>

<%= link_to 'Back', lecturers_path %>

app/views/lecturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lecturer.name %>
</p>

<p>
  <b>Last name:</b>
  <%= @lecturer.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @lecturer.age %>
</p>

<p>
  <b>Profile:</b>
  <%= @lecturer.profile %>
</p>

<p>
  <b>Foto:</b>
  <%= @lecturer.foto %>
</p>

<p>
  <b>Tenant:</b>
  <%= @lecturer.tenant %>
</p>


<%= link_to 'Edit', edit_lecturer_path(@lecturer) %> |
<%= link_to 'Back', lecturers_path %>